"$schema" = 'https://starship.rs/config-schema.json'
palette = 'catppuccin_mocha'
add_newline= false

format = """
 $directory\
$character\
"""
right_format = """
$git_status\
$git_branch\ 
$git_metrics\ 
$all \
"""

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:purple)[❯](bold fg:peach)[❯](bold fg:teal)'
error_symbol = '[❯](bold fg:red)[❯](bold fg:red)[❯](bold fg:red)'
vimcmd_symbol = '[❯](bold fg:maroon)[❯](bold fg:maroon)[❯](bold fg:maroon)'
vimcmd_replace_one_symbol = '[❯](bold fg:purple)[❯](bold fg:purple)[❯](bold fg:purple)'
vimcmd_replace_symbol = '[❯](bold fg:pink)[❯](bold fg:pink)[❯](bold fg:pink)'
vimcmd_visual_symbol = '[❯](bold fg:orange)[❯](bold fg:orange)[❯](bold fg:orange)'

# right prompt uses left space padding
[git_branch]
symbol = " "
style = 'green'
format = '[$symbol](fg:peach)[$branch ](bold fg:blue)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

# ~/.config/starship.toml

# ~/.config/starship.toml

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
style = "red"
format="[$symbol]($style)"
shell = ["sh"]

[cmd_duration]
min_time = 1000 # 10 secs 
format = " [󰥔 ](fg:text)[$duration]($style)"

# directory configuration

[directory]
read_only = " 󰌾"
style = "fg:teal"
format = "[◆](bold fg:peach)[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"workbench" = "󰲋 "
".config" = " "
"Clang" = " "
"React" = ""
"Go" =  " "
"Rust" = "󱘗 "
Svelte = ""
Node = "󰎙 "
Bash = " "
Sql = " "
Haskell = " "
Python = " "

# Languages

[c]
symbol = " "
format = "[$symbol](fg:blue)[$version](fg:text)"

[python]
symbol = " "
format = "[$symbol](fg:yellow)[$version](fg:text)"

[rust]
symbol = "󱘗 "
format = "[$symbol](fg:red)[$version](fg:text)"

[golang]
symbol = " "
format = "[$symbol](fg:cyan)[$version](fg:text)"

[haskell]
symbol = " "
format = "[$symbol](fg:purple)[$version](fg:text)"

[java]
symbol = " "
format = "[$symbol](fg:orange)[$version](fg:text)"

[nodejs]
symbol = " "
format = "[$symbol](fg:green)[$version](fg:text)"

# Tools 

[package]
symbol = "󰏗 "
format = "[$symbol](fg:peach)"

[aws]
symbol = "  "

[docker_context]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[meson]
symbol = "󰔷 "
format = "[$symbol](fg:cyan)[$version](fg:text)"

# Color Palettes 

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
