require("manuel.plugins-setup")
require("manuel.core.options")
require("manuel.core.keymap")
require("manuel.core.colorschme")

-- Plugins calls
require("manuel.plugins.nvim-tree")
require("manuel.plugins.comment")
require("manuel.plugins.telescope")
require("manuel.plugins.nvim-cmp")
require("manuel.plugins.lsp.mason")
require("manuel.plugins.lualine")
require("manuel.plugins.lsp.lspconfig")
require("manuel.plugins.lsp.lspsaga")
require("manuel.plugins.autopairs")
require("manuel.plugins.lsp.null-ls")
require("manuel.plugins.treesitter")
require("manuel.plugins.gitsigns")
